name: Run tests & Upload coverage to Codecov

on:
  push:
    branches: [main]

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.6

    - name: Install dependencies
      run: poetry install

    - name: Run tests & Generate XML coverage report
      run: |
        poetry run pytest --cov=. --cov-report=xml

    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v1
